# Generated by go2rpm 1.14.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/derailed/k9s
%global goipath         github.com/derailed/k9s
Version:                0.32.5

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
🐶 Kubernetes CLI To Manage Your Clusters In Style!}

%global golicenses      COPYING LICENSE
%global godocs          README.md change_logs/release_0.1.1.md\\\
                        change_logs/release_0.1.10.md\\\
                        change_logs/release_0.1.11.md\\\
                        change_logs/release_0.1.2.md\\\
                        change_logs/release_0.1.3.md\\\
                        change_logs/release_0.1.4.md\\\
                        change_logs/release_0.1.5.md\\\
                        change_logs/release_0.1.6.md\\\
                        change_logs/release_0.1.7.md\\\
                        change_logs/release_0.1.8.md\\\
                        change_logs/release_0.1.9.md\\\
                        change_logs/release_0.10.0.md\\\
                        change_logs/release_0.10.1.md\\\
                        change_logs/release_0.10.2.md\\\
                        change_logs/release_0.10.3.md\\\
                        change_logs/release_0.10.4.md\\\
                        change_logs/release_0.10.5.md\\\
                        change_logs/release_0.10.6.md\\\
                        change_logs/release_0.10.7.md\\\
                        change_logs/release_0.10.8.md\\\
                        change_logs/release_0.10.9.md\\\
                        change_logs/release_0.11.0.md\\\
                        change_logs/release_0.11.1.md\\\
                        change_logs/release_0.11.2.md\\\
                        change_logs/release_0.11.3.md\\\
                        change_logs/release_0.12.0.md\\\
                        change_logs/release_0.2.0.md\\\
                        change_logs/release_0.2.1.md\\\
                        change_logs/release_0.2.2.md\\\
                        change_logs/release_0.2.3.md\\\
                        change_logs/release_0.2.4.md\\\
                        change_logs/release_0.2.5.md\\\
                        change_logs/release_0.2.6.md\\\
                        change_logs/release_0.3.0.md\\\
                        change_logs/release_0.3.1.md\\\
                        change_logs/release_0.3.2.md\\\
                        change_logs/release_0.3.3.md\\\
                        change_logs/release_0.4.0.md\\\
                        change_logs/release_0.4.1.md\\\
                        change_logs/release_0.4.2.md\\\
                        change_logs/release_0.4.3.md\\\
                        change_logs/release_0.4.4.md\\\
                        change_logs/release_0.4.5.md\\\
                        change_logs/release_0.4.6.md\\\
                        change_logs/release_0.4.7.md\\\
                        change_logs/release_0.4.8.md\\\
                        change_logs/release_0.5.0.md\\\
                        change_logs/release_0.5.1.md\\\
                        change_logs/release_0.5.2.md\\\
                        change_logs/release_0.6.0.md\\\
                        change_logs/release_0.6.1.md\\\
                        change_logs/release_0.6.2.md\\\
                        change_logs/release_0.6.3.md\\\
                        change_logs/release_0.6.4.md\\\
                        change_logs/release_0.6.5.md\\\
                        change_logs/release_0.6.6.md\\\
                        change_logs/release_0.6.7.md\\\
                        change_logs/release_0.7.0.md\\\
                        change_logs/release_0.7.1.md\\\
                        change_logs/release_0.7.10.md\\\
                        change_logs/release_0.7.11.md\\\
                        change_logs/release_0.7.12.md\\\
                        change_logs/release_0.7.13.md\\\
                        change_logs/release_0.7.2.md\\\
                        change_logs/release_0.7.3.md\\\
                        change_logs/release_0.7.4.md\\\
                        change_logs/release_0.7.5.md\\\
                        change_logs/release_0.7.6.md\\\
                        change_logs/release_0.7.7.md\\\
                        change_logs/release_0.7.8.md\\\
                        change_logs/release_0.7.9.md\\\
                        change_logs/release_0.8.0.md\\\
                        change_logs/release_0.8.1.md\\\
                        change_logs/release_0.8.2.md\\\
                        change_logs/release_0.8.3.md\\\
                        change_logs/release_0.8.4.md\\\
                        change_logs/release_0.9.0.md\\\
                        change_logs/release_0.9.1.md\\\
                        change_logs/release_0.9.2.md\\\
                        change_logs/release_0.9.3.md\\\
                        change_logs/release_v0.13.0.md\\\
                        change_logs/release_v0.13.1.md\\\
                        change_logs/release_v0.13.2.md\\\
                        change_logs/release_v0.13.3.md\\\
                        change_logs/release_v0.13.4.md\\\
                        change_logs/release_v0.13.5.md\\\
                        change_logs/release_v0.13.6.md\\\
                        change_logs/release_v0.13.7.md\\\
                        change_logs/release_v0.13.8.md\\\
                        change_logs/release_v0.14.0.md\\\
                        change_logs/release_v0.14.1.md\\\
                        change_logs/release_v0.15.0.md\\\
                        change_logs/release_v0.15.1.md\\\
                        change_logs/release_v0.15.2.md\\\
                        change_logs/release_v0.16.0.md\\\
                        change_logs/release_v0.16.1.md\\\
                        change_logs/release_v0.17.0.md\\\
                        change_logs/release_v0.17.1.md\\\
                        change_logs/release_v0.17.2.md\\\
                        change_logs/release_v0.17.3.md\\\
                        change_logs/release_v0.17.4.md\\\
                        change_logs/release_v0.17.5.md\\\
                        change_logs/release_v0.17.6.md\\\
                        change_logs/release_v0.17.7.md\\\
                        change_logs/release_v0.18.0.md\\\
                        change_logs/release_v0.18.1.md\\\
                        change_logs/release_v0.19.0.md\\\
                        change_logs/release_v0.19.1.md\\\
                        change_logs/release_v0.19.2.md\\\
                        change_logs/release_v0.19.3.md\\\
                        change_logs/release_v0.19.4.md\\\
                        change_logs/release_v0.19.5.md\\\
                        change_logs/release_v0.19.6.md\\\
                        change_logs/release_v0.19.7.md\\\
                        change_logs/release_v0.20.0.md\\\
                        change_logs/release_v0.20.1.md\\\
                        change_logs/release_v0.20.2.md\\\
                        change_logs/release_v0.20.3.md\\\
                        change_logs/release_v0.20.4.md\\\
                        change_logs/release_v0.20.5.md\\\
                        change_logs/release_v0.21.0.md\\\
                        change_logs/release_v0.21.1.md\\\
                        change_logs/release_v0.21.10.md\\\
                        change_logs/release_v0.21.2.md\\\
                        change_logs/release_v0.21.3.md\\\
                        change_logs/release_v0.21.4.md\\\
                        change_logs/release_v0.21.5.md\\\
                        change_logs/release_v0.21.6.md\\\
                        change_logs/release_v0.21.7.md\\\
                        change_logs/release_v0.21.8.md\\\
                        change_logs/release_v0.21.9.md\\\
                        change_logs/release_v0.22.0.md\\\
                        change_logs/release_v0.22.1.md\\\
                        change_logs/release_v0.23.0.md\\\
                        change_logs/release_v0.23.1.md\\\
                        change_logs/release_v0.23.10.md\\\
                        change_logs/release_v0.23.2.md\\\
                        change_logs/release_v0.23.3.md\\\
                        change_logs/release_v0.23.4.md\\\
                        change_logs/release_v0.23.5.md\\\
                        change_logs/release_v0.23.6.md\\\
                        change_logs/release_v0.23.7.md\\\
                        change_logs/release_v0.23.8.md\\\
                        change_logs/release_v0.23.9.md\\\
                        change_logs/release_v0.24.0.md\\\
                        change_logs/release_v0.24.1.md\\\
                        change_logs/release_v0.24.10.md\\\
                        change_logs/release_v0.24.11.md\\\
                        change_logs/release_v0.24.12.md\\\
                        change_logs/release_v0.24.13.md\\\
                        change_logs/release_v0.24.14.md\\\
                        change_logs/release_v0.24.15.md\\\
                        change_logs/release_v0.24.2.md\\\
                        change_logs/release_v0.24.3.md\\\
                        change_logs/release_v0.24.4.md\\\
                        change_logs/release_v0.24.5.md\\\
                        change_logs/release_v0.24.6.md\\\
                        change_logs/release_v0.24.7.md\\\
                        change_logs/release_v0.24.8.md\\\
                        change_logs/release_v0.24.9.md\\\
                        change_logs/release_v0.25.0.md\\\
                        change_logs/release_v0.25.1.md\\\
                        change_logs/release_v0.25.10.md\\\
                        change_logs/release_v0.25.11.md\\\
                        change_logs/release_v0.25.12.md\\\
                        change_logs/release_v0.25.13.md\\\
                        change_logs/release_v0.25.14.md\\\
                        change_logs/release_v0.25.15.md\\\
                        change_logs/release_v0.25.16.md\\\
                        change_logs/release_v0.25.17.md\\\
                        change_logs/release_v0.25.18.md\\\
                        change_logs/release_v0.25.19.md\\\
                        change_logs/release_v0.25.2.md\\\
                        change_logs/release_v0.25.20.md\\\
                        change_logs/release_v0.25.21.md\\\
                        change_logs/release_v0.25.3.md\\\
                        change_logs/release_v0.25.4.md\\\
                        change_logs/release_v0.25.5.md\\\
                        change_logs/release_v0.25.6.md\\\
                        change_logs/release_v0.25.7.md\\\
                        change_logs/release_v0.25.8.md\\\
                        change_logs/release_v0.25.9.md\\\
                        change_logs/release_v0.26.0.md\\\
                        change_logs/release_v0.26.1.md\\\
                        change_logs/release_v0.26.2.md\\\
                        change_logs/release_v0.26.3.md\\\
                        change_logs/release_v0.26.4.md\\\
                        change_logs/release_v0.26.5.md\\\
                        change_logs/release_v0.26.6.md\\\
                        change_logs/release_v0.26.7.md\\\
                        change_logs/release_v0.27.0.md\\\
                        change_logs/release_v0.27.1.md\\\
                        change_logs/release_v0.27.2.md\\\
                        change_logs/release_v0.27.3.md\\\
                        change_logs/release_v0.27.4.md\\\
                        change_logs/release_v0.28.0.md\\\
                        change_logs/release_v0.28.1.md\\\
                        change_logs/release_v0.28.2.md\\\
                        change_logs/release_v0.29.0.md\\\
                        change_logs/release_v0.29.1.md\\\
                        change_logs/release_v0.30.0.md\\\
                        change_logs/release_v0.30.1.md\\\
                        change_logs/release_v0.30.2.md\\\
                        change_logs/release_v0.30.3.md\\\
                        change_logs/release_v0.30.4.md\\\
                        change_logs/release_v0.30.5.md\\\
                        change_logs/release_v0.30.6.md\\\
                        change_logs/release_v0.30.7.md\\\
                        change_logs/release_v0.30.8.md\\\
                        change_logs/release_v0.31.0.md\\\
                        change_logs/release_v0.31.1.md\\\
                        change_logs/release_v0.31.2.md\\\
                        change_logs/release_v0.31.3.md\\\
                        change_logs/release_v0.31.4.md\\\
                        change_logs/release_v0.31.5.md\\\
                        change_logs/release_v0.31.6.md\\\
                        change_logs/release_v0.31.7.md\\\
                        change_logs/release_v0.31.8.md\\\
                        change_logs/release_v0.31.9.md\\\
                        change_logs/release_v0.32.0.md\\\
                        change_logs/release_v0.32.1.md\\\
                        change_logs/release_v0.32.2.md\\\
                        change_logs/release_v0.32.3.md\\\
                        change_logs/release_v0.32.4.md\\\
                        change_logs/release_v0.32.5.md plugins/README.md

Name:           k9s
Release:        %autorelease
Summary:        🐶 Kubernetes CLI To Manage Your Clusters In Style

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/k9s %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license COPYING LICENSE
%doc README.md change_logs/release_0.1.1.md change_logs/release_0.1.10.md
%doc change_logs/release_0.1.11.md change_logs/release_0.1.2.md
%doc change_logs/release_0.1.3.md change_logs/release_0.1.4.md
%doc change_logs/release_0.1.5.md change_logs/release_0.1.6.md
%doc change_logs/release_0.1.7.md change_logs/release_0.1.8.md
%doc change_logs/release_0.1.9.md change_logs/release_0.10.0.md
%doc change_logs/release_0.10.1.md change_logs/release_0.10.2.md
%doc change_logs/release_0.10.3.md change_logs/release_0.10.4.md
%doc change_logs/release_0.10.5.md change_logs/release_0.10.6.md
%doc change_logs/release_0.10.7.md change_logs/release_0.10.8.md
%doc change_logs/release_0.10.9.md change_logs/release_0.11.0.md
%doc change_logs/release_0.11.1.md change_logs/release_0.11.2.md
%doc change_logs/release_0.11.3.md change_logs/release_0.12.0.md
%doc change_logs/release_0.2.0.md change_logs/release_0.2.1.md
%doc change_logs/release_0.2.2.md change_logs/release_0.2.3.md
%doc change_logs/release_0.2.4.md change_logs/release_0.2.5.md
%doc change_logs/release_0.2.6.md change_logs/release_0.3.0.md
%doc change_logs/release_0.3.1.md change_logs/release_0.3.2.md
%doc change_logs/release_0.3.3.md change_logs/release_0.4.0.md
%doc change_logs/release_0.4.1.md change_logs/release_0.4.2.md
%doc change_logs/release_0.4.3.md change_logs/release_0.4.4.md
%doc change_logs/release_0.4.5.md change_logs/release_0.4.6.md
%doc change_logs/release_0.4.7.md change_logs/release_0.4.8.md
%doc change_logs/release_0.5.0.md change_logs/release_0.5.1.md
%doc change_logs/release_0.5.2.md change_logs/release_0.6.0.md
%doc change_logs/release_0.6.1.md change_logs/release_0.6.2.md
%doc change_logs/release_0.6.3.md change_logs/release_0.6.4.md
%doc change_logs/release_0.6.5.md change_logs/release_0.6.6.md
%doc change_logs/release_0.6.7.md change_logs/release_0.7.0.md
%doc change_logs/release_0.7.1.md change_logs/release_0.7.10.md
%doc change_logs/release_0.7.11.md change_logs/release_0.7.12.md
%doc change_logs/release_0.7.13.md change_logs/release_0.7.2.md
%doc change_logs/release_0.7.3.md change_logs/release_0.7.4.md
%doc change_logs/release_0.7.5.md change_logs/release_0.7.6.md
%doc change_logs/release_0.7.7.md change_logs/release_0.7.8.md
%doc change_logs/release_0.7.9.md change_logs/release_0.8.0.md
%doc change_logs/release_0.8.1.md change_logs/release_0.8.2.md
%doc change_logs/release_0.8.3.md change_logs/release_0.8.4.md
%doc change_logs/release_0.9.0.md change_logs/release_0.9.1.md
%doc change_logs/release_0.9.2.md change_logs/release_0.9.3.md
%doc change_logs/release_v0.13.0.md change_logs/release_v0.13.1.md
%doc change_logs/release_v0.13.2.md change_logs/release_v0.13.3.md
%doc change_logs/release_v0.13.4.md change_logs/release_v0.13.5.md
%doc change_logs/release_v0.13.6.md change_logs/release_v0.13.7.md
%doc change_logs/release_v0.13.8.md change_logs/release_v0.14.0.md
%doc change_logs/release_v0.14.1.md change_logs/release_v0.15.0.md
%doc change_logs/release_v0.15.1.md change_logs/release_v0.15.2.md
%doc change_logs/release_v0.16.0.md change_logs/release_v0.16.1.md
%doc change_logs/release_v0.17.0.md change_logs/release_v0.17.1.md
%doc change_logs/release_v0.17.2.md change_logs/release_v0.17.3.md
%doc change_logs/release_v0.17.4.md change_logs/release_v0.17.5.md
%doc change_logs/release_v0.17.6.md change_logs/release_v0.17.7.md
%doc change_logs/release_v0.18.0.md change_logs/release_v0.18.1.md
%doc change_logs/release_v0.19.0.md change_logs/release_v0.19.1.md
%doc change_logs/release_v0.19.2.md change_logs/release_v0.19.3.md
%doc change_logs/release_v0.19.4.md change_logs/release_v0.19.5.md
%doc change_logs/release_v0.19.6.md change_logs/release_v0.19.7.md
%doc change_logs/release_v0.20.0.md change_logs/release_v0.20.1.md
%doc change_logs/release_v0.20.2.md change_logs/release_v0.20.3.md
%doc change_logs/release_v0.20.4.md change_logs/release_v0.20.5.md
%doc change_logs/release_v0.21.0.md change_logs/release_v0.21.1.md
%doc change_logs/release_v0.21.10.md change_logs/release_v0.21.2.md
%doc change_logs/release_v0.21.3.md change_logs/release_v0.21.4.md
%doc change_logs/release_v0.21.5.md change_logs/release_v0.21.6.md
%doc change_logs/release_v0.21.7.md change_logs/release_v0.21.8.md
%doc change_logs/release_v0.21.9.md change_logs/release_v0.22.0.md
%doc change_logs/release_v0.22.1.md change_logs/release_v0.23.0.md
%doc change_logs/release_v0.23.1.md change_logs/release_v0.23.10.md
%doc change_logs/release_v0.23.2.md change_logs/release_v0.23.3.md
%doc change_logs/release_v0.23.4.md change_logs/release_v0.23.5.md
%doc change_logs/release_v0.23.6.md change_logs/release_v0.23.7.md
%doc change_logs/release_v0.23.8.md change_logs/release_v0.23.9.md
%doc change_logs/release_v0.24.0.md change_logs/release_v0.24.1.md
%doc change_logs/release_v0.24.10.md change_logs/release_v0.24.11.md
%doc change_logs/release_v0.24.12.md change_logs/release_v0.24.13.md
%doc change_logs/release_v0.24.14.md change_logs/release_v0.24.15.md
%doc change_logs/release_v0.24.2.md change_logs/release_v0.24.3.md
%doc change_logs/release_v0.24.4.md change_logs/release_v0.24.5.md
%doc change_logs/release_v0.24.6.md change_logs/release_v0.24.7.md
%doc change_logs/release_v0.24.8.md change_logs/release_v0.24.9.md
%doc change_logs/release_v0.25.0.md change_logs/release_v0.25.1.md
%doc change_logs/release_v0.25.10.md change_logs/release_v0.25.11.md
%doc change_logs/release_v0.25.12.md change_logs/release_v0.25.13.md
%doc change_logs/release_v0.25.14.md change_logs/release_v0.25.15.md
%doc change_logs/release_v0.25.16.md change_logs/release_v0.25.17.md
%doc change_logs/release_v0.25.18.md change_logs/release_v0.25.19.md
%doc change_logs/release_v0.25.2.md change_logs/release_v0.25.20.md
%doc change_logs/release_v0.25.21.md change_logs/release_v0.25.3.md
%doc change_logs/release_v0.25.4.md change_logs/release_v0.25.5.md
%doc change_logs/release_v0.25.6.md change_logs/release_v0.25.7.md
%doc change_logs/release_v0.25.8.md change_logs/release_v0.25.9.md
%doc change_logs/release_v0.26.0.md change_logs/release_v0.26.1.md
%doc change_logs/release_v0.26.2.md change_logs/release_v0.26.3.md
%doc change_logs/release_v0.26.4.md change_logs/release_v0.26.5.md
%doc change_logs/release_v0.26.6.md change_logs/release_v0.26.7.md
%doc change_logs/release_v0.27.0.md change_logs/release_v0.27.1.md
%doc change_logs/release_v0.27.2.md change_logs/release_v0.27.3.md
%doc change_logs/release_v0.27.4.md change_logs/release_v0.28.0.md
%doc change_logs/release_v0.28.1.md change_logs/release_v0.28.2.md
%doc change_logs/release_v0.29.0.md change_logs/release_v0.29.1.md
%doc change_logs/release_v0.30.0.md change_logs/release_v0.30.1.md
%doc change_logs/release_v0.30.2.md change_logs/release_v0.30.3.md
%doc change_logs/release_v0.30.4.md change_logs/release_v0.30.5.md
%doc change_logs/release_v0.30.6.md change_logs/release_v0.30.7.md
%doc change_logs/release_v0.30.8.md change_logs/release_v0.31.0.md
%doc change_logs/release_v0.31.1.md change_logs/release_v0.31.2.md
%doc change_logs/release_v0.31.3.md change_logs/release_v0.31.4.md
%doc change_logs/release_v0.31.5.md change_logs/release_v0.31.6.md
%doc change_logs/release_v0.31.7.md change_logs/release_v0.31.8.md
%doc change_logs/release_v0.31.9.md change_logs/release_v0.32.0.md
%doc change_logs/release_v0.32.1.md change_logs/release_v0.32.2.md
%doc change_logs/release_v0.32.3.md change_logs/release_v0.32.4.md
%doc change_logs/release_v0.32.5.md plugins/README.md
%{_bindir}/k9s
%endif

%gopkgfiles

%changelog
%autochangelog
